### PR TITLE
Updated for Silex v2

### PR DESCRIPTION
**Pull request by Rarst**
Fixes https://github.com/bobthecow/mustache.php/issues/302

### CODE REVIEW

**Comment by jaminellis** [comment]
Looks good to me, and would be very good to have this workin in 2.0. I wonder about ^2.0 in the composer file for silex though - perhaps "silex/silex": "~2.0" - just in case silex 3.0 emerges at somepoint and changes how it works with Pimple again?

**Comment by Rarst** [comment]
> I wonder about ^2.0 in the composer file for silex though - perhaps "silex/silex": "~2.0" - just in case silex 3.0 emerges at somepoint and changes how it works with Pimple again?

These are equivalent in this case? Neither allows `3.*` version. See [caret operator](https://getcomposer.org/doc/articles/versions.md#caret).

**Comment by Rarst** [comment]
Anything I can do to nudge this along? :) Have some downstream dependency updates pending on it...

**Comment by bobthecow** [comment]
Oh, sorry, I dropped the ball on this. I'll merge it shortly :)

**Comment by Rarst** [comment]
Thank you for the merge and release! :)

I have added it to the list of v2–compatible providers in Silex wiki https://github.com/silexphp/Silex/wiki/Third-Party-ServiceProviders-for-Silex-2.x#templating

**Comment by bobthecow** [comment]
:+1:

**Pull request merged**
